<a href="https://colab.research.google.com/github/Mithunprb/sudoku_solver/blob/main/sudoku_solver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sudoku Solver
**Using Python** <br>
grid is numpy matrix of 8x8 rows and columns<br>



In [ ]:
grid = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,4,1,9,0,0,5],
        [0,0,0,0,8,0,0,7,9]]

In [ ]:
import numpy as np
print(np.matrix(grid))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [ ]:
def possible(y, x, n):
  global grid
  for i in range(0, 9):
    if grid[y][i] == n:
      return False
  for i in range(0, 9):
    if grid[i][x] == n:
      return False
  x0 = (x//3) * 3
  y0 = (y//3) * 3

  for i in range(0, 3):
    for j in range(0, 3):
      if grid[y0+i][x0+j] == n:
        return False
      
  return True

In [ ]:
def solve():
  global grid
  for y in range(9):
    for x in range(9):
      if grid[y][x] == 0:
        for n in range(1, 10):
          if possible(y, x, n):
            grid[y][x] = n
            solve()
            grid[y][x] = 0
        
  yield np.matrix(grid)

In [ ]:
ans = solve()

In [ ]:
next(ans)

matrix([[5, 3, 1, 2, 7, 4, 8, 9, 0],
        [6, 2, 4, 1, 9, 5, 3, 0, 7],
        [0, 9, 8, 3, 0, 0, 1, 6, 2],
        [8, 1, 2, 5, 6, 7, 4, 0, 3],
        [4, 5, 6, 8, 0, 3, 7, 2, 1],
        [7, 0, 3, 9, 2, 1, 5, 0, 6],
        [1, 6, 5, 7, 3, 0, 2, 8, 4],
        [2, 8, 7, 4, 1, 9, 0, 3, 5],
        [3, 4, 0, 0, 8, 2, 6, 7, 9]])